theme: minima
title: Journey of a New Research Physicist
author: Eric Stimpson
description: Starting from my first summer in grad school, I will document my journey to becoming a professional physicist. I will focus on topics related to my specific field of research and sprinkle in some personal thoughts.
